### PR TITLE
Update photo.js to render all images as list item - #5.

### PR DESCRIPTION
**Pull request by saif-malik-01**
Change remove div and make photo component only list item to Render all images as list items #5 .

### CODE REVIEW

**Review by Tishasoumya-02 — COMMENTED** [review]
This is not the aim of the issue #5 .

**Comment by saif-malik-01** [comment]
Can you please elaborate the issue then.

**Comment by Tishasoumya-02** [comment]
'images' is a 2-d array storing images from the API, ul tag renders it with the help of li in Photo.js file so if  you could think of some other logic to render images  instead of storing them in an array will be appreciated.

**Comment by saif-malik-01** [comment]
Ah got it, can we use flat list ?

**Comment by Tishasoumya-02** [comment]
> Ah got it, can we use flat list ?

We can try that

**Comment by saif-malik-01** [comment]
@Tishasoumya-02 Images is a 1d array and there is no other way to render images without array.

**Comment by saif-malik-01** [comment]
Can you please elaborate, why you using grid in photo.js .

**Pull request closed without merging**
